### ISSUE TITLE
We should check that all user provided functions can be correctly loaded.

### ISSUE THREAD

**Issue by jhorbulyk** [elasticio/elasticio-buildpack-nodejs#8]
We should check that all user provided functions can be correctly loaded. If not we should raise an exception at build time and not run time.

**Comment by zubairov** [comment]
I think that should be a bug to Sailor - when ``salior`` is resolving a module from the ``component.json`` it should report the bug properly. We shouldn't do it at build-time

**Comment by zubairov** [comment]
@jhorbulyk there is actually a handling for some of these cases, see here:

https://github.com/elasticio/sailor-nodejs/blob/master/spec/component_reader.spec.js#L86

and

https://github.com/elasticio/sailor-nodejs/blob/master/spec/component_reader.spec.js#L109

We just need the same for:
 * Action
 * verifyCredentials

**Comment by jhorbulyk** [comment]
Closing in favor of https://github.com/elasticio/platform/issues/25
